# Generated by Django 4.0 on 2021-12-28 09:42

import apps.markets.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, default="'BTC/USDT'", max_length=20)),
                ('status', models.CharField(choices=[('TRADING', 'Trading'), ('BREAK', 'Break')], db_index=True, default='TRADING', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('1m', 'Minute'), ('1h', 'Hour'), ('1d', 'Day')], db_index=True, default='1m', max_length=2)),
                ('open_time', models.DateTimeField(db_index=True)),
                ('open', apps.markets.fields.PriceField(decimal_places=8, default=0, max_digits=30)),
                ('high', apps.markets.fields.PriceField(decimal_places=8, default=0, max_digits=30)),
                ('low', apps.markets.fields.PriceField(decimal_places=8, default=0, max_digits=30)),
                ('close', apps.markets.fields.PriceField(decimal_places=8, default=0, max_digits=30)),
                ('volume', apps.markets.fields.AmountField(decimal_places=8, default=0, max_digits=30)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.market')),
            ],
            options={
                'ordering': ['-open_time'],
            },
        ),
        migrations.AddIndex(
            model_name='kline',
            index=models.Index(fields=['open_time', 'market', 'interval'], name='markets_kli_open_ti_046963_idx'),
        ),
        migrations.AddIndex(
            model_name='kline',
            index=models.Index(fields=['-open_time'], name='open_time_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kline',
            unique_together={('market', 'interval', 'open_time')},
        ),
    ]
